--- # install java and python3
- hosts: node
  become: true
  tasks:
    - name: install java and python3
      apt:
        name: openjdk-11-jdk,openjdk-11-jre,python3
        state: latest
    - name: setup jenkins
      command:
        cmd: bash /home/ubuntu/ansible/jenkins.sh
